name: Continous Integration (Api Server)

on: [pull_request]

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '20'
    - name: Install dependencies
      run: npm install
    - name: Run ESLint
      run: npx eslint . --ext .js,.jsx,.ts,.tsx # Adjust file extensions as needed
