version: '3.8'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
  prisma-dev:
    image: node:latest
    depends_on:
      - postgres
    volumes:
      - ./:/app
    working_dir: /app
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
    command: sh -c "npm install && npx prisma migrate dev"
    stdin_open: true
    tty: true
volumes:
  postgres-data:
