name: 'Build Packages'
description: 'Builds the packages'
runs:
    using: 'composite'
    steps:
        - name: Setup Node.js
          uses: actions/setup-node@v2
          with:
              node-version: '20.x'
        - run: npm i -g corepack
          shell: bash
        - run: corepack enable
          shell: bash
        - run: yarn --version
          shell: bash
        - run: yarn prebuild
          shell: bash
        - run: yarn build
          shell: bash
