version: '3.8'
services:
  api:
    build: .
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      API_PORT: 3000
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run dev

