name: CI Packages Environment

on:
    pull_request:
        branches: [main]
        paths:
            - 'packages/environment/**'

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - name: Build packages
              uses: ./.github/actions/build-monorepo

            - name: Run Chai Tests (unit + api)
              working-directory: ./packages/environment
              run: yarn test
