name: CI Packages Environment

on:
    pull_request:
        branches: [main]
        paths:
            - 'packages/environment/**'

jobs:
    build:
        runs-on: ubuntu-latest

        defaults:
            run:
                working-directory: ./packages/environment

        env:
            API_PORT: 3000
            DB_URL: "should-not-be-passed"
            AUTH_SERVICE_URL: "should-not-be-passed"

        steps:
            - uses: actions/checkout@v3
            
            - name: Build packages
              uses: ./.github/actions/build-monorepo

            - name: Run Chai Tests (unit + api)
              run: yarn test
