name: CI Packages Environment

on:
    pull_request:
        branches: [main]
        paths:
            - 'packages/environment/**'

jobs:
    build:
        runs-on: ubuntu-latest

        defaults:
            run:
                working-directory: ./packages/environment

        env:
            API_PORT: 3000

        steps:
            - uses: actions/checkout@v2
            - name: Setup Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: '20.x'
            - name: Build packages
                uses: ./.github/actions/build-packages
            - name: Install dependencies using yarn
              run: yarn install --frozen-lockfile
            - name: Run Chai Tests (unit + api)
              run: yarn test
