name: CI Rest API

on:
    pull_request:
        branches: [main]
        paths:
            - 'services/rest-api/**'

jobs:
    build:
        runs-on: ubuntu-latest

        env:
            API_PORT: 3000

        steps:
            - uses: actions/checkout@v2

            - name: Setup Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: '20.x'
                  cache: 'yarn'

            - name: Build packages
              uses: ./.github/actions/build-packages-at-root

            - name: Install dependencies with Yarn
              working-directory: ./services/rest-api
              run: yarn

            - name: Proceed with your build steps
              working-directory: ./services/rest-api
              run: |
                  yarn test
                  yarn build
                  yarn start:prod:dry
