name: CI Rest API

on:
    pull_request:
        branches: [main]
        paths:
            - 'services/rest-api/**'

jobs:
    build:
        runs-on: ubuntu-latest

        defaults:
            run:
                working-directory: ./services/rest-api

        env:
            API_PORT: 3000

        steps:
            - uses: actions/checkout@v2
            - name: Setup Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: '20.x'
            - name: Build packages
                uses: ./.github/actions/build-packages
            - name: Install dependencies using yarn
              run: yarn install --frozen-lockfile
            - name: Run Chai Tests (unit + api)
              run: yarn test
            - name: Dry run
              run: yarn build && yarn start:prod:dry
