name: CI Rest API

on:
    pull_request:
        branches: [main]
        paths:
            - 'services/rest-api/**'

jobs:
    build:
        runs-on: ubuntu-latest
        env:
            API_PORT: 3000
        steps:
            - uses: actions/checkout@v3
            
            - name: Build packages
              uses: ./.github/actions/build-monorepo

            - name: Run Tests (Api + Unit)
              working-directory: ./services/rest-api
              run: yarn test

            - name: Build TypeScript
              working-directory: ./services/rest-api
              run: yarn build

            - name: Dry Run code
              working-directory: ./services/rest-api
              run: yarn start:prod:dry
