name: CI Rest API

on:
    pull_request:
        branches: [main]
        paths:
            - 'services/rest-api/**'

jobs:
    build:
        runs-on: ubuntu-latest

        env:
            API_PORT: 3000

        steps:
            - uses: actions/checkout@v2

            - name: Setup Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: '20.x'

            - name: Install yarn
              run: npm install -g yarn

            - name: Set specific yarn version
              run: yarn set version 4.1.0

            - name: Verify Yarn Version
              run: yarn --version

            - name: Install dependencies with Yarn
              run: yarn

            - name: Proceed with your build steps
              working-directory: ./services/rest-api
              run: |
                  yarn test
                  yarn build
                  yarn start:prod:dry
