name: Lint Code Base

on:
    pull_request:
        branches: [never]
    workflow_dispatch:

jobs:
    eslint:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            
            - name: Build packages
              uses: ./.github/actions/build-monorepo
              
            - name: Run ESLint
              run: yarn lint
