name: Lint Code Base

on:
    pull_request:
        branches: [main]
    workflow_dispatch:

jobs:
    eslint:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Setup Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: '20'
            - name: Build packages
              uses: ./.github/actions/build-packages-at-root.yaml
            - name: Install Dependencies
              run: yarn
            - name: Run ESLint
              run: yarn lint
